import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useMemo, useState } from "react";
import { groupColorHex, playerColorHex } from "@/theme";
function PropertyCard({ game, cellIndex, selected, onToggle }) {
    const cell = game.board[cellIndex];
    const property = game.properties.find((item) => item.cellIndex === cellIndex);
    const owner = property?.ownerId ? game.players.find((player) => player.id === property.ownerId) : undefined;
    return (_jsxs("button", { className: `rounded-xl border p-2 text-left text-xs transition ${selected ? "border-gold bg-gold/10" : "border-borderSoft bg-panel/70"}`, onClick: onToggle, type: "button", children: [_jsxs("div", { className: "mb-1 flex items-center justify-between gap-2", children: [_jsx("span", { className: "font-semibold text-emerald-100", children: cell?.name }), _jsx("span", { className: "h-2.5 w-5 rounded", style: { background: cell?.group ? groupColorHex[cell.group] ?? "#64748B" : "#64748B" } })] }), _jsxs("div", { className: "space-y-0.5 text-[11px] text-emerald-300", children: [_jsxs("div", { children: ["\u0426\u0435\u043D\u0430: \uD83E\uDE99 ", property?.scaledPrice] }), _jsxs("div", { children: ["\u0423\u0440\u043E\u0432\u0435\u043D\u044C: ", property?.level ?? 0] }), _jsxs("div", { children: ["\u0410\u0440\u0435\u043D\u0434\u0430: \uD83E\uDE99 ", property ? Math.round(property.scaledBaseRent * (1 + property.level * 0.4)) : 0] }), _jsxs("div", { className: "flex items-center gap-1", children: ["\u0412\u043B\u0430\u0434\u0435\u043B\u0435\u0446:", _jsx("span", { className: "rounded px-1 text-black", style: { background: owner ? playerColorHex[owner.color] : "#6B7280" }, children: owner?.name ?? "Bank" })] }), property?.shielded && _jsx("div", { children: "\uD83D\uDEE1\uFE0F \u0429\u0438\u0442" })] })] }));
}
export function TradeModal({ open, game, meId, onClose, onCreate, onAccept, onReject, onCounter, onCancel }) {
    const [selectedPlayer, setSelectedPlayer] = useState("");
    const [offered, setOffered] = useState([]);
    const [requested, setRequested] = useState([]);
    const [moneyFrom, setMoneyFrom] = useState(0);
    const [moneyTo, setMoneyTo] = useState(0);
    const me = game.players.find((player) => player.id === meId);
    const target = game.players.find((player) => player.id === selectedPlayer);
    const myProperties = useMemo(() => game.properties.filter((property) => property.ownerId === meId).map((property) => property.cellIndex), [game.properties, meId]);
    const targetProperties = useMemo(() => game.properties.filter((property) => property.ownerId === selectedPlayer).map((property) => property.cellIndex), [game.properties, selectedPlayer]);
    const incoming = game.trades.filter((trade) => trade.toPlayerId === meId && trade.status === "pending");
    const outgoing = game.trades.filter((trade) => trade.fromPlayerId === meId && trade.status === "pending");
    if (!open || !me)
        return null;
    return (_jsx("div", { className: "fixed inset-0 z-40 flex items-center justify-center bg-black/70 p-3", children: _jsxs("div", { className: "glass-panel flex h-[90vh] w-full max-w-6xl flex-col rounded-card border p-4", children: [_jsxs("div", { className: "mb-3 flex items-center justify-between", children: [_jsx("h3", { className: "text-lg font-semibold text-gold", children: "\u041E\u0431\u043C\u0435\u043D\u044B" }), _jsx("button", { className: "rounded border border-borderSoft px-2 py-1 text-xs", onClick: onClose, children: "\u0417\u0430\u043A\u0440\u044B\u0442\u044C" })] }), _jsxs("div", { className: "grid flex-1 gap-3 overflow-hidden lg:grid-cols-[1.2fr_1fr]", children: [_jsxs("div", { className: "overflow-hidden rounded-xl border border-borderSoft p-3", children: [_jsx("div", { className: "mb-2 text-xs uppercase tracking-wide text-emerald-300", children: "\u041D\u043E\u0432\u043E\u0435 \u043F\u0440\u0435\u0434\u043B\u043E\u0436\u0435\u043D\u0438\u0435" }), _jsxs("select", { className: "mb-3 w-full rounded-lg border border-borderSoft bg-panel px-2 py-2 text-sm", value: selectedPlayer, onChange: (event) => {
                                        setSelectedPlayer(event.target.value);
                                        setOffered([]);
                                        setRequested([]);
                                    }, children: [_jsx("option", { value: "", children: "\u0412\u044B\u0431\u0440\u0430\u0442\u044C \u0438\u0433\u0440\u043E\u043A\u0430" }), game.players
                                            .filter((player) => player.id !== meId && !player.isBankrupt && !player.debtMode)
                                            .map((player) => (_jsx("option", { value: player.id, children: player.name }, player.id)))] }), _jsxs("div", { className: "grid gap-3 md:grid-cols-2", children: [_jsxs("div", { children: [_jsx("div", { className: "mb-2 text-xs text-emerald-300", children: "\u041C\u043E\u0438 \u0443\u043B\u0438\u0446\u044B" }), _jsx("div", { className: "max-h-52 space-y-2 overflow-y-auto pr-1", children: myProperties.map((cellIndex) => (_jsx(PropertyCard, { game: game, cellIndex: cellIndex, selected: offered.includes(cellIndex), onToggle: () => setOffered((current) => current.includes(cellIndex)
                                                            ? current.filter((item) => item !== cellIndex)
                                                            : [...current, cellIndex]) }, cellIndex))) })] }), _jsxs("div", { children: [_jsxs("div", { className: "mb-2 text-xs text-emerald-300", children: ["\u0423\u043B\u0438\u0446\u044B ", target?.name ?? "игрока"] }), _jsx("div", { className: "max-h-52 space-y-2 overflow-y-auto pr-1", children: targetProperties.map((cellIndex) => (_jsx(PropertyCard, { game: game, cellIndex: cellIndex, selected: requested.includes(cellIndex), onToggle: () => setRequested((current) => current.includes(cellIndex)
                                                            ? current.filter((item) => item !== cellIndex)
                                                            : [...current, cellIndex]) }, cellIndex))) })] })] }), _jsxs("div", { className: "mt-3 grid gap-2 md:grid-cols-2", children: [_jsxs("label", { className: "text-xs text-emerald-300", children: ["\u042F \u0434\u0430\u044E \u0434\u0435\u043D\u0435\u0433", _jsx("input", { className: "mt-1 w-full rounded-lg border border-borderSoft bg-panel px-2 py-2 text-sm", type: "number", min: 0, value: moneyFrom, onChange: (event) => setMoneyFrom(Number(event.target.value)) })] }), _jsxs("label", { className: "text-xs text-emerald-300", children: ["\u042F \u043F\u0440\u043E\u0448\u0443 \u0434\u0435\u043D\u0435\u0433", _jsx("input", { className: "mt-1 w-full rounded-lg border border-borderSoft bg-panel px-2 py-2 text-sm", type: "number", min: 0, value: moneyTo, onChange: (event) => setMoneyTo(Number(event.target.value)) })] })] }), _jsx("button", { className: "mt-3 rounded-xl bg-gradient-to-r from-green to-gold px-4 py-2 text-sm font-semibold text-black disabled:cursor-not-allowed disabled:opacity-45", disabled: !selectedPlayer, onClick: () => onCreate({
                                        toPlayerId: selectedPlayer,
                                        offeredPropertyIds: offered,
                                        requestedPropertyIds: requested,
                                        moneyFrom,
                                        moneyTo
                                    }), children: "\u041E\u0442\u043F\u0440\u0430\u0432\u0438\u0442\u044C \u043F\u0440\u0435\u0434\u043B\u043E\u0436\u0435\u043D\u0438\u0435" })] }), _jsxs("div", { className: "grid gap-3 overflow-hidden", children: [_jsxs("div", { className: "overflow-hidden rounded-xl border border-borderSoft p-3", children: [_jsx("div", { className: "mb-2 text-xs uppercase tracking-wide text-emerald-300", children: "\u0412\u0445\u043E\u0434\u044F\u0449\u0438\u0435" }), _jsxs("div", { className: "max-h-56 space-y-2 overflow-y-auto text-xs", children: [incoming.length === 0 && _jsx("div", { className: "text-emerald-400", children: "\u041D\u0435\u0442 \u0432\u0445\u043E\u0434\u044F\u0449\u0438\u0445 \u043F\u0440\u0435\u0434\u043B\u043E\u0436\u0435\u043D\u0438\u0439" }), incoming.map((trade) => {
                                                    const sender = game.players.find((player) => player.id === trade.fromPlayerId);
                                                    return (_jsxs("div", { className: "rounded-xl border border-borderSoft bg-panel/70 p-2", children: [_jsxs("div", { className: "font-semibold text-gold", children: [sender?.name, " \u043F\u0440\u0435\u0434\u043B\u0430\u0433\u0430\u0435\u0442 \u043E\u0431\u043C\u0435\u043D"] }), _jsxs("div", { className: "text-emerald-300", children: ["\u0414\u0435\u043D\u044C\u0433\u0438: \uD83E\uDE99 ", trade.moneyFrom, " / \uD83E\uDE99 ", trade.moneyTo] }), _jsxs("div", { className: "mt-2 flex flex-wrap gap-1.5", children: [_jsx("button", { className: "rounded bg-green/70 px-2 py-1 text-black", onClick: () => onAccept(trade.id), children: "\u041F\u0440\u0438\u043D\u044F\u0442\u044C" }), _jsx("button", { className: "rounded bg-danger/80 px-2 py-1", onClick: () => onReject(trade.id), children: "\u041E\u0442\u043A\u043B\u043E\u043D\u0438\u0442\u044C" }), _jsx("button", { className: "rounded border border-borderSoft px-2 py-1", onClick: () => onCounter(trade.id, {
                                                                            offeredPropertyIds: trade.requestedPropertyIds,
                                                                            requestedPropertyIds: trade.offeredPropertyIds,
                                                                            moneyFrom: trade.moneyTo,
                                                                            moneyTo: trade.moneyFrom
                                                                        }), children: "\u0412\u0441\u0442\u0440\u0435\u0447\u043D\u043E\u0435" })] })] }, trade.id));
                                                })] })] }), _jsxs("div", { className: "overflow-hidden rounded-xl border border-borderSoft p-3", children: [_jsx("div", { className: "mb-2 text-xs uppercase tracking-wide text-emerald-300", children: "\u0418\u0441\u0445\u043E\u0434\u044F\u0449\u0438\u0435" }), _jsxs("div", { className: "max-h-56 space-y-2 overflow-y-auto text-xs", children: [outgoing.length === 0 && _jsx("div", { className: "text-emerald-400", children: "\u041D\u0435\u0442 \u0438\u0441\u0445\u043E\u0434\u044F\u0449\u0438\u0445 \u043F\u0440\u0435\u0434\u043B\u043E\u0436\u0435\u043D\u0438\u0439" }), outgoing.map((trade) => {
                                                    const receiver = game.players.find((player) => player.id === trade.toPlayerId);
                                                    return (_jsxs("div", { className: "rounded-xl border border-borderSoft bg-panel/70 p-2", children: [_jsxs("div", { className: "font-semibold text-gold", children: ["\u0414\u043B\u044F ", receiver?.name] }), _jsxs("div", { className: "text-emerald-300", children: ["\u0414\u0435\u043D\u044C\u0433\u0438: \uD83E\uDE99 ", trade.moneyFrom, " / \uD83E\uDE99 ", trade.moneyTo] }), _jsx("button", { className: "mt-2 rounded border border-borderSoft px-2 py-1", onClick: () => onCancel(trade.id), children: "\u041E\u0442\u043C\u0435\u043D\u0438\u0442\u044C" })] }, trade.id));
                                                })] })] })] })] })] }) }));
}
