export const CHANCE_CARDS = [
    { id: "neg-1", category: "negative", title: "Tax Audit", description: "Pay a surprise fine.", icon: "💸", effectType: "money", value: -220 },
    { id: "neg-2", category: "negative", title: "Street Repairs", description: "Pay for emergency repairs.", icon: "🛠️", effectType: "money", value: -180 },
    { id: "neg-3", category: "negative", title: "Pay Every Rival", description: "Pay each active player.", icon: "🪙", effectType: "pay_all", value: 90 },
    { id: "neg-4", category: "negative", title: "Miss a Turn", description: "Skip one turn.", icon: "⏱️", effectType: "skip_turns", value: 1 },
    { id: "neg-5", category: "negative", title: "Frozen Plans", description: "Cannot upgrade for 2 turns.", icon: "❄️", effectType: "cannot_upgrade_turns", value: 2 },
    { id: "neg-6", category: "negative", title: "Court Order", description: "Go directly to jail.", icon: "🚓", effectType: "go_to_jail" },
    { id: "neg-7", category: "negative", title: "Broken Barrier", description: "Lose one shield from your property.", icon: "🛡️", effectType: "lose_shield" },
    { id: "neg-8", category: "negative", title: "Minor Fire", description: "Downgrade one of your properties by one level.", icon: "🔥", effectType: "downgrade_property" },
    { id: "neg-9", category: "negative", title: "Major Collapse", description: "Reset one of your properties to level 0.", icon: "🏚️", effectType: "reset_property" },
    { id: "neg-10", category: "negative", title: "Bank Fee", description: "Pay a service fee.", icon: "🏦", effectType: "money", value: -260 },
    { id: "neg-11", category: "negative", title: "Public Fine", description: "Pay each rival a civic fee.", icon: "📜", effectType: "pay_all", value: 120 },
    { id: "neg-12", category: "negative", title: "Delay Permit", description: "Skip two turns.", icon: "🧾", effectType: "skip_turns", value: 2 },
    { id: "chaos-1", category: "chaos", title: "Sneaky Pickpocket", description: "Steal coins from a random rival.", icon: "🕵️", effectType: "steal_money", value: 180 },
    { id: "chaos-2", category: "chaos", title: "Royal Tribute", description: "All rivals pay you.", icon: "👑", effectType: "receive_from_all", value: 90 },
    { id: "chaos-3", category: "chaos", title: "Chaotic Exchange", description: "Swap a random property with a rival.", icon: "🔀", effectType: "swap_random_property" },
    { id: "chaos-4", category: "chaos", title: "Hostile Takeover", description: "Steal a random unshielded property.", icon: "⚔️", effectType: "steal_random_property" },
    { id: "chaos-5", category: "chaos", title: "Sabotage", description: "Break one level on rival property.", icon: "💥", effectType: "break_enemy_upgrade" },
    { id: "chaos-6", category: "chaos", title: "Demolition", description: "Reset random rival property to bank.", icon: "🧨", effectType: "delete_enemy_property" },
    { id: "chaos-7", category: "chaos", title: "Shield Breaker", description: "Remove one rival shield.", icon: "🪓", effectType: "remove_enemy_shield" },
    { id: "chaos-8", category: "chaos", title: "Icy Decree", description: "Freeze rival property upgrades for 2 turns.", icon: "🧊", effectType: "freeze_property", value: 2 },
    { id: "chaos-9", category: "chaos", title: "Portal Jump", description: "Teleport to a random cell.", icon: "🌀", effectType: "teleport" },
    { id: "chaos-10", category: "chaos", title: "Treasure Heist", description: "Steal bigger amount from random rival.", icon: "🎭", effectType: "steal_money", value: 260 },
    { id: "pos-1", category: "positive", title: "Lucky Bonus", description: "Receive bonus coins.", icon: "✨", effectType: "money", value: 220 },
    { id: "pos-2", category: "positive", title: "Dividend Payout", description: "Receive a larger payout.", icon: "💰", effectType: "money", value: 320 },
    { id: "pos-3", category: "positive", title: "Guard Station", description: "Place shield on one of your properties.", icon: "🛡️", effectType: "gain_shield" },
    { id: "pos-4", category: "positive", title: "Builder Grant", description: "Get one free upgrade.", icon: "🏗️", effectType: "free_upgrade" },
    { id: "pos-5", category: "positive", title: "Freedom Pass", description: "Get out of jail free card.", icon: "🔓", effectType: "jail_free_card" },
    { id: "pos-6", category: "positive", title: "Buyout Rebate", description: "Gain buyout discount for 2 turns.", icon: "📉", effectType: "buyout_discount", value: 2 },
    { id: "pos-7", category: "positive", title: "Investor Gift", description: "All rivals pay you a fee.", icon: "📈", effectType: "receive_from_all", value: 70 },
    { id: "pos-8", category: "positive", title: "Royal Contractor", description: "Gain another free upgrade.", icon: "🏰", effectType: "free_upgrade" }
];
